PROMPTS = {
  "fun": {"truth": [
    "Quel message gênant as-tu déjà envoyé par erreur ?",
    "Qui dans ce groupe te fait le plus rire ?",
    "Quel est ton talent inutile le plus bizarre ?",
    "Quelle est la chose la plus enfantine que tu fais encore ?",
    "Quel est ton dernier petit mensonge ?",
    "Si tu pouvais échanger ta vie avec quelqu'un pendant 24h, qui choisirais-tu ?",
    "Quel emoji te représente le mieux et pourquoi ?",
    "Quel est ton pire souvenir de honte en public ?",
    "Quelle est la série que tu peux regarder en boucle sans t'en lasser ?",
    "Quel est le surnom le plus ridicule qu'on t'ait donné ?",
    "Quel est ton plus grand guilty pleasure ?",
    "Si tu devais manger un seul plat pour le reste de ta vie, lequel ?",
    "Quelle est la dernière bêtise que tu as faite ?",
    "Quel film d'animation est ton préféré et pourquoi ?",
    "Quel est ton souvenir d'enfance le plus drôle ?",
    "Si tu gagnais au loto demain, quelle est la première chose que tu ferais ?",
    "Quel est ton plus grand talent caché ?",
    "Quelle est la chose la plus étrange que tu aies déjà mangée ?",
    "Quel est ton animal totem et pourquoi ?",
    "As-tu déjà eu une obsession bizarre étant petit ?",
    "Quel est le truc le plus idiot que tu aies fait pour impressionner quelqu'un ?",
    "Quelle est ta phobie la plus ridicule ?",
    "Quel est ton plus grand luxe quotidien ?",
    "Si tu pouvais être invisible pendant une heure, que ferais-tu ?",
    "Quelle est la pire mode que tu aies suivie ?",
    "Quel est le compliment le plus étrange que tu aies reçu ?",
    "Si tu étais un personnage de fiction, qui serais-tu ?",
    "Quel est le rêve le plus bizarre dont tu te souviennes ?",
    "Qu'est-ce que tu fais quand personne ne te regarde ?",
    "Quelle est ta chanson préférée à chanter sous la douche ?"],
    "dare": [
    "Envoie un vocal de 5 secondes où tu chantes ton prénom.",
    "Change ta photo de profil pendant 10 minutes avec un emoji de ton choix.",
    "Écris un compliment exagéré à la personne de ton choix dans le groupe.",
    "Parle uniquement avec des emojis pendant 3 messages.",
    "Envoie une phrase dramatique comme si tu jouais dans une série.",
    "Fais une déclaration d'amitié ultra solennelle dans le groupe.",
    "Imite un animateur radio dans un message vocal.",
    "Décris ton humeur du moment comme un bulletin météo.",
    "Envoie une photo de ton frigo actuel (pas de triche).",
    "Invente un slogan pour le groupe et poste-le.",
    "Fais deviner un film en 3 emojis seulement.",
    "Raconte une blague nulle en message vocal.",
    "Écris un mini-poireau (message vide) mais avec un effet dramatique.",
    "Partage ton dernier mème enregistré.",
    "Prends un selfie avec une expression la plus bizarre possible et poste-le.",
    "Réponds au prochain message de quelqu'un uniquement avec des gifs.",
    "Invente un nouveau prénom pour chaque membre du groupe.",
    "Envoie un message en parlant de toi à la troisième personne.",
    "Choisis un mot au hasard et utilise-le 5 fois dans la conversation.",
    "Poste un statut WhatsApp absurde pendant 5 minutes.",
    "Fais une imitation d'un membre du groupe en vocal.",
    "Écris une critique de film imaginaire de 2 lignes.",
    "Envoie un message avec une police bizarre (style générateur en ligne).",
    "Fais un top 3 des pires tenues que tu aies portées.",
    "Décris ton matin comme si c'était le script d'un film d'action.",
    "Envoie la première photo de ta galerie (sans regarder).",
    "Fais une déclaration d'amour à un objet du quotidien.",
    "Poste un mème que toi seul trouves drôle.",
    "Écris une règle absurde que tout le groupe doit suivre pour ce soir.",
    "Fais une démonstration de ta meilleure danse en vocal."
  ]},
  "amis": {"truth": [
    "Quelle vérité sur toi surprendrait vraiment le groupe ?",
    "Quel est le plus gros risque que tu n'as jamais osé prendre ?",
    "As-tu déjà ignoré quelqu'un exprès ici ou ailleurs ?",
    "Quelle est la critique qu'on te fait souvent et qui te touche ?",
    "Quel est ton plus grand regret récent ?",
    "Qu'est-ce que tu caches souvent derrière l'humour ?",
    "Quelle est la dernière fois où tu t'es senti vraiment jaloux ?",
    "Quelle peur te bloque encore aujourd'hui ?",
    "As-tu déjà dit 'je t'aime' sans le penser vraiment ?",
    "Quel est le plus gros mensonge que tu aies raconté à tes parents ?",
    "As-tu déjà trahi la confiance de quelqu'un ?",
    "Qu'est-ce que tu n'as jamais avoué à personne ?",
    "Quelle est la chose que tu fais quand tu es seul et que tu cacherais ?",
    "As-tu déjà pleuré devant un film et lequel ?",
    "Quelle est la plus grande pression que tu ressens en ce moment ?",
    "As-tu déjà eu honte de quelqu'un dans ta vie ?",
    "Quelle est ta plus grande insécurité ?",
    "As-tu déjà espionné quelqu'un sur les réseaux ?",
    "Quel est le pire conseil que tu aies donné ?",
    "As-tu déjà volé quelque chose ?",
    "Qu'est-ce qui te réveille la nuit ?",
    "As-tu déjà fait semblant d'être quelqu'un d'autre en ligne ?",
    "Quel est le secret que tu gardes depuis le plus longtemps ?",
    "As-tu déjà été jaloux de la réussite de quelqu'un ?",
    "Quelle est la chose la plus dure qu'on t'ait dite ?",
    "As-tu déjà fait du mal à quelqu'un volontairement ?",
    "Qu'est-ce que tu changeras chez toi si tu pouvais ?",
    "As-tu déjà été toxique dans une relation ?",
    "Quel est le plus grand sacrifice que tu aies fait ?",
    "As-tu déjà regretté d'avoir été honnête ?"],
    "dare": [
    "Envoie un vocal où tu te vends comme une star pendant 10 secondes.",
    "Écris une phrase honnête sur ton défaut principal.",
    "Laisse le groupe choisir ton prochain statut WhatsApp.",
    "Raconte une anecdote embarrassante en 2 lignes maximum.",
    "Envoie un message en mode motivation extrême comme un coach.",
    "Fais une mini-confession que tu n'aurais pas dite spontanément.",
    "Choisis quelqu'un dans le groupe et donne-lui une vérité brutale mais gentille.",
    "Écris une phrase sur ce que tu dois améliorer chez toi.",
    "Envoie une photo de toi à 13 ans (moche ou pas, on assume).",
    "Fais une liste de 3 choses que tu détestes chez toi.",
    "Envoie un vocal où tu cries un mot au hasard.",
    "Écris un message que tu n'enverrais jamais à ton crush.",
    "Raconte ton pire échec en 3 phrases.",
    "Fais le portrait chinois de toi-même (si j'étais...).",
    "Écris une lettre d'excuses à quelqu'un que tu as blessé.",
    "Poste une story WhatsApp qui restera 10 minutes.",
    "Envoie un audax (audio maximum) de 30 secondes sur un sujet imposé.",
    "Fais une critique honnête de toi-même en 5 points.",
    "Écris ce que tu penses vraiment du groupe en général (honnêteté totale).",
    "Choisis entre deux options que le groupe te donnera.",
    "Envoie le screen de ta dernière conversation avec ta mère.",
    "Fais un classement des membres du groupe du plus au moins mature.",
    "Révèle le montant de ton dernier achat impulsif.",
    "Écris un défaut de chaque membre du groupe (constructif).",
    "Envoie un message que tu as envoyé par erreur un jour.",
    "Chante une chanson triste en vocal de 10 secondes.",
    "Fais une confession sur un crush passé ou présent.",
    "Écris ton plus grand regret en une phrase.",
    "Poste quelque chose que tu n'as jamais dit à personne.",
    "Fais un bilan honnête de ta vie actuelle en 30 secondes."
  ]},
  "soft": {"truth": [
    "Quel geste romantique te ferait fondre instantanément ?",
    "Quel type de message te fait le plus plaisir à recevoir ?",
    "Quelle est ta définition d'une vraie complicité ?",
    "As-tu déjà eu un crush secret sur quelqu'un de ton entourage ?",
    "Quel détail chez une personne t'attire en premier ?",
    "Quel souvenir tendre te revient souvent ?",
    "Tu préfères une grande déclaration ou des petites attentions ?",
    "Quel serait ton rendez-vous idéal ?",
    "Quel est le mot le plus doux de la langue française selon toi ?",
    "As-tu déjà été amoureux en secret longtemps ?",
    "Quel est le plus beau compliment que tu aies reçu ?",
    "Qu'est-ce qui te fait fondre chez quelqu'un ?",
    "Quelle chanson d'amour te touche le plus ?",
    "Décris ta définition du couple parfait.",
    "Quel est ton plus beau souvenir de Saint-Valentin ?",
    "Que ferais-tu pour impressionner quelqu'un qui te plaît ?",
    "As-tu déjà écrit une lettre d'amour ?",
    "Quel est ton film romantique préféré ?",
    "Qu'est-ce que l'amour pour toi en une phrase ?",
    "Quel défaut deviens-tu supportable chez quelqu'un que tu aimes ?",
    "As-tu déjà eu le cœur brisé ?",
    "Quel est le plus beau prénom que tu donnerais à ton enfant ?",
    "Préfères-tu la douceur ou la passion ?",
    "Quel est ton plus grand rêve en amour ?",
    "As-tu déjà fait le premier pas ?",
    "Que penses-tu des relations à distance ?",
    "Quel est le message le plus touchant que tu aies reçu ?",
    "Décris ta pire expérience en amour.",
    "Quel est le petit geste qui te fait craquer ?",
    "À quoi ressemble ta journée parfaite en amoureux ?"],
    "dare": [
    "Écris une phrase romantique comme dans un film.",
    "Envoie un compliment sincère à la personne de ton choix.",
    "Décris ton rendez-vous parfait en une seule phrase.",
    "Écris une déclaration poétique avec au moins 3 emojis.",
    "Rédige un mini-message doux que quelqu'un aimerait recevoir.",
    "Dis quel trait rend une personne irrésistible selon toi.",
    "Écris une phrase de séduction élégante et drôle.",
    "Fais un top 3 de ce qui te touche le plus chez quelqu'un.",
    "Envoie une voix douce de 10 secondes avec un message tendre.",
    "Écris un haïku d'amour original.",
    "Fais une déclaration à la personne de ton choix (même pour rire).",
    "Décris ton coup de foudre idéal.",
    "Écris un petit mot que quelqu'un aimerait trouver dans sa poche.",
    "Invente un surnom mignon pour chaque membre du groupe.",
    "Rédige un message de bonne nuit ultra romantique.",
    "Fais une promesse solennelle d'amitié ou d'amour.",
    "Écris un poème de 4 lignes sur l'amour.",
    "Décris la plus belle preuve d'amour que tu connaisses.",
    "Choisis quelqu'un du groupe et dis pourquoi cette personne est spéciale.",
    "Écris une définition de l'amour comme si tu écrivais un dictionnaire.",
    "Envoie un vocal en chuchotant une phrase douce.",
    "Fais une liste de 5 choses que tu veux vivre en amour.",
    "Écris un message que tu aimerais recevoir un jour.",
    "Décris ton âme sœur en 5 adjectifs.",
    "Rédige une invitation à un rendez-vous imaginaire parfait.",
    "Envoie une citation d'amour qui te correspond.",
    "Fais une déclaration d'amour à la vie en général.",
    "Écris un micro-scénario de rencontre romantique.",
    "Dis la chose la plus douce que tu aies dite à quelqu'un.",
    "Fais un compliment unique et personnalisé à chaque joueur."
  ]},
  "hot": {"truth": [
    "Quel genre de message te fait rougir immédiatement ?",
    "As-tu déjà relu une conversation juste parce qu'elle te plaisait trop ?",
    "Qu'est-ce qui te rend le plus attirant selon toi ?",
    "Quel compliment un peu osé aimerais-tu recevoir ?",
    "Quelle situation te fait perdre tes moyens ?",
    "Quel est ton plus gros point faible en séduction ?",
    "As-tu déjà laissé planer un flirt sans l'avouer ?",
    "Quel regard ou attitude te déstabilise le plus ?",
    "Quel est le message le plus coquin que tu aies envoyé ?",
    "As-tu déjà flirté avec quelqu'un présent dans ce groupe ?",
    "Qu'est-ce qui te rend le plus charmant séducteur ?",
    "Quel est ton pire défaut en séduction ?",
    "As-tu déjà embrassé quelqu'un par défi ?",
    "Quel est le compliment le plus efficace selon toi ?",
    "As-tu déjà dragué quelqu'un sans t'en rendre compte ?",
    "Quelle est la chose la plus audacieuse que tu aies faite par amour ?",
    "Qu'est-ce qui te fait craquer physiquement en premier ?",
    "As-tu déjà eu un plan cul ou une relation sans lendemain ?",
    "Quel est ton plus grand fantasme (soft) ?",
    "As-tu déjà envoyé une photo osée ?",
    "Quelle est la pire tentative de drague que tu aies vue ?",
    "As-tu déjà eu un coup d'un soir ?",
    "Quel est ton plus gros turn-on ?",
    "As-tu déjà espionné le téléphone de quelqu'un ?",
    "Quel est le surnom le plus hot qu'on t'ait donné ?",
    "Décris ton plus beau baiser.",
    "As-tu déjà regretté un flirt ?",
    "Qu'est-ce que tu ferais si personne ne te jugeait ?",
    "As-tu déjà eu une aventure avec un ou une collègue ?",
    "Quel est le message que tu aimerais recevoir en secret ?"],
    "dare": [
    "Écris une phrase de flirt soft mais assumée.",
    "Décris ton énergie de séduction en 3 mots.",
    "Envoie un vocal avec une voix ultra confiante pendant 5 secondes.",
    "Fais une phrase mystérieuse qui pourrait intriguer quelqu'un.",
    "Écris le compliment le plus audacieux mais classe que tu peux imaginer.",
    "Décris ton type idéal en une ligne percutante.",
    "Écris une phrase qui donne envie de répondre tout de suite.",
    "Rédige une mini-intro de DM parfaite.",
    "Envoie une question piège à quelqu'un du groupe.",
    "Décris ton regard séduction en 3 adjectifs.",
    "Écris un message que tu enverrais à 2h du matin.",
    "Fais une déclaration en mode mauvais garçon ou fille fatale.",
    "Envoie un vocal avec un ton de voix qui fait craquer.",
    "Invente un jeu de mots osé mais élégant.",
    "Écris une phrase de rapprochement progressive en 3 étapes.",
    "Décris ton attitude en soirée en mode séduction.",
    "Choisis quelqu'un dans le groupe et invente son alter ego séducteur.",
    "Envoie une phrase d'accroche originale pour un DM.",
    "Fais une proposition en mode 'à moitié sérieux, à moitié pour rire'.",
    "Écris un compliment sur le sourire de quelqu'un du groupe.",
    "Décris ton parfum ou l'odeur que tu préfères chez quelqu'un.",
    "Envoie une invitation mystérieuse à boire un verre.",
    "Fais une déclaration visuelle avec une emoji composition.",
    "Écris une phrase qui pourrait être une légende Instagram parfaite.",
    "Décris ce que tu portes en ce moment de manière suggestive.",
    "Envoie un message en mode 'je pense à toi' sans dire à qui.",
    "Fais un compliment décalé mais bien senti à un membre.",
    "Écris une phrase de rupture fictive ultra dramatique.",
    "Invente un challenge pour le groupe à faire en privé.",
    "Rédige une bio Tinder pour un membre du groupe."
  ]}
}

GAGES = [
  "Envoie un emoji de toi en train de faire n'importe quoi en vocal.",
  "Change ton surnom dans le groupe en 'Le/La Boss' pour 10 min.",
  "Poste une photo de ton réfrigérateur.",
  "Chante la première ligne d'une chanson au hasard en vocal.",
  "Écris un compliment à chaque personne du groupe.",
  "Envoie une devinette débile et oblige quelqu'un à répondre.",
  "Parle en verlan pendant 3 messages.",
  "Fais une révérence ou un salut militaire en gif.",
  "Invente un nouveau prénom pour toi et utilise-le tout le tour.",
  "Laisse le groupe choisir une mission pour toi dans WhatsApp.",
  "Poste un mème qui décrit ta vie actuelle.",
  "Envoie un vocal de 15 secondes ou tu racontes ta journée en 5 mots max.",
  "Enlève un accessoire (montre, bracelet, etc.) jusqu'au prochain tour.",
  "Ta prochaine phrase doit être une question, quoi qu'il arrive.",
  "Décris le dernier film que tu as vu en 3 emojis."
]

CATEGORIES = {"fun": "FUN", "amis": "ENTRE AMIS", "soft": "SOFT", "hot": "HOT"}
